development:
  adapter: mysql2
  host: localhost
  username: root
  password: password
  database: whiteboard_development

test:
  adapter: postgresql
  host: localhost
  database: whiteboard_test

production:
  adapter: postgresql
  host: localhost
  database: whiteboard_production
